name = "edgetree-api"
type = "javascript"

account_id = "1c1f1e0e790dbe378722231e83953bd3"
workers_dev = true
route = "edgetree.sinclair.software/api/*"
zone_id = "e1b35f5e84cad9150ddd59df16d2847b"


[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
